name: Branch Checks

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        env:
          COVERAGE: 1
        run: |
          bundle exec rake ci
